Repository auth0/Auth0.Android, pull requests merged in 2020-08, with the labels that each got.

#322 Update README with callback threading note
  README.md
Labels: waiting for customer

#325 Patch Key alias migration for Secure Credentials Manager
  auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.java
  auth0/src/test/java/com/auth0/android/authentication/storage/SecureCredentialsManagerTest.java
Labels: CH: Fixed, small

#326 Release 1.24.1
  CHANGELOG.md
  README.md
Labels: tiny

#327 Add a note to the CHANGELOG file about the recent release
  CHANGELOG.md
Labels: tiny
