Repository auth0/Auth0.Android, pull requests merged in 2020-12, with the labels that each got.

#377 Add credentials manager thread-safe note [SDK-2078]
  README.md
Labels: review:small

#380 Increase the required minimum API to 21
  README.md
  auth0/build.gradle
  auth0/src/main/java/com/auth0/android/authentication/storage/CryptoUtil.java
  auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.java
  auth0/src/main/java/com/auth0/android/provider/WebAuthActivity.java
  auth0/src/main/java/com/auth0/android/request/internal/OkHttpClientFactory.java
  auth0/src/test/java/com/auth0/android/Auth0Test.java
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.java
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationExceptionTest.java
  auth0/src/test/java/com/auth0/android/authentication/request/DatabaseConnectionRequestTest.java
  auth0/src/test/java/com/auth0/android/authentication/request/DelegationRequestTest.java
  auth0/src/test/java/com/auth0/android/authentication/request/ProfileRequestTest.java
  auth0/src/test/java/com/auth0/android/authentication/request/SignUpRequestTest.java
  auth0/src/test/java/com/auth0/android/authentication/request/TokenRequestTest.java
  auth0/src/test/java/com/auth0/android/authentication/storage/CredentialsManagerTest.java
  auth0/src/test/java/com/auth0/android/authentication/storage/CryptoUtilTest.java
  auth0/src/test/java/com/auth0/android/authentication/storage/SecureCredentialsManagerTest.java
  auth0/src/test/java/com/auth0/android/authentication/storage/SharedPreferencesStorageTest.java
  auth0/src/test/java/com/auth0/android/provider/AsymmetricSignatureVerifierTest.java
  auth0/src/test/java/com/auth0/android/provider/AuthProviderTest.java
  auth0/src/test/java/com/auth0/android/provider/AuthenticationActivityTest.java
  auth0/src/test/java/com/auth0/android/provider/AuthorizeResultTest.java
  auth0/src/test/java/com/auth0/android/provider/BrowserPickerTest.java
  auth0/src/test/java/com/auth0/android/provider/CallbackHelperTest.java
  auth0/src/test/java/com/auth0/android/provider/CustomTabsControllerTest.java
  auth0/src/test/java/com/auth0/android/provider/CustomTabsOptionsTest.java
  auth0/src/test/java/com/auth0/android/provider/IdTokenVerifierTest.java
  auth0/src/test/java/com/auth0/android/provider/LogoutManagerTest.java
  auth0/src/test/java/com/auth0/android/provider/OAuthManagerTest.java
  auth0/src/test/java/com/auth0/android/provider/PKCETest.java
  auth0/src/test/java/com/auth0/android/provider/PermissionHandlerTest.java
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.java
  auth0/src/test/java/com/auth0/android/request/internal/AuthenticationErrorBuilderTest.java
  auth0/src/test/java/com/auth0/android/request/internal/BaseAuthenticationRequestTest.java
  auth0/src/test/java/com/auth0/android/request/internal/JwksGsonTest.java
  auth0/src/test/java/com/auth0/android/request/internal/OkHttpClientFactoryTest.java
Labels: CH: Breaking Change, medium

#379 Add Kotlin dependency
  auth0/build.gradle
  build.gradle
  gradle.properties
Labels: CH: Changed, small

#383 Remove deprecated methods
  V2_MIGRATION_GUIDE.md
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.java
  auth0/src/main/java/com/auth0/android/authentication/request/ProfileRequest.java
  auth0/src/main/java/com/auth0/android/authentication/request/SignUpRequest.java
  auth0/src/main/java/com/auth0/android/provider/WebAuthProvider.java
  auth0/src/main/java/com/auth0/android/util/Base64.java
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.java
  auth0/src/test/java/com/auth0/android/authentication/request/SignUpRequestTest.java
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.java
Labels: CH: Removed, medium

#384 Add basic Sample app
  sample/.gitignore
  sample/build.gradle
  sample/consumer-rules.pro
  sample/proguard-rules.pro
  sample/src/main/AndroidManifest.xml
  sample/src/main/java/com/auth0/sample/DatabaseLoginFragment.kt
  sample/src/main/java/com/auth0/sample/MainActivity.kt
  sample/src/main/res/layout/activity_main.xml
  sample/src/main/res/layout/fragment_database_login.xml
  sample/src/main/res/navigation/nav_graph.xml
  sample/src/main/res/values/strings.xml
  sample/src/main/res/values/themes.xml
  settings.gradle
Labels: CH: Added, medium

#385 Request interfaces refactor
  V2_MIGRATION_GUIDE.md
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.java
  auth0/src/main/java/com/auth0/android/authentication/request/DatabaseConnectionRequest.java
  auth0/src/main/java/com/auth0/android/authentication/request/DelegationRequest.java
  auth0/src/main/java/com/auth0/android/authentication/request/ProfileRequest.java
  auth0/src/main/java/com/auth0/android/authentication/request/SignUpRequest.java
  auth0/src/main/java/com/auth0/android/authentication/request/TokenRequest.java
  auth0/src/main/java/com/auth0/android/authentication/storage/CredentialsManager.java
  auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.java
  auth0/src/main/java/com/auth0/android/management/UsersAPIClient.java
  auth0/src/main/java/com/auth0/android/request/AuthRequest.java
  auth0/src/main/java/com/auth0/android/request/AuthenticationRequest.java
  auth0/src/main/java/com/auth0/android/request/AuthorizableRequest.java
  auth0/src/main/java/com/auth0/android/request/ParameterizableRequest.java
  auth0/src/main/java/com/auth0/android/request/Request.java
  auth0/src/main/java/com/auth0/android/request/internal/BaseAuthenticationRequest.java
  auth0/src/main/java/com/auth0/android/request/internal/BaseRequest.java
  auth0/src/main/java/com/auth0/android/request/internal/RequestFactory.java
  auth0/src/main/java/com/auth0/android/request/internal/SimpleRequest.java
  auth0/src/test/java/com/auth0/android/authentication/request/AuthenticationRequestMock.java
  auth0/src/test/java/com/auth0/android/authentication/request/DatabaseConnectionRequestTest.java
  auth0/src/test/java/com/auth0/android/authentication/request/DelegationRequestTest.java
  auth0/src/test/java/com/auth0/android/authentication/request/ProfileRequestTest.java
  auth0/src/test/java/com/auth0/android/authentication/request/RequestMock.java
  auth0/src/test/java/com/auth0/android/authentication/request/SignUpRequestTest.java
  auth0/src/test/java/com/auth0/android/authentication/request/TokenRequestTest.java
  auth0/src/test/java/com/auth0/android/authentication/storage/CredentialsManagerTest.java
  auth0/src/test/java/com/auth0/android/authentication/storage/SecureCredentialsManagerTest.java
  auth0/src/test/java/com/auth0/android/request/internal/MockAuthenticationRequest.java
  auth0/src/test/java/com/auth0/android/request/internal/MockRequest.java
  auth0/src/test/java/com/auth0/android/request/internal/RequestFactoryTest.java
Labels: CH: Breaking Change, large

#386 Only support OIDC Conformant Authentication Flow
  README.md
  V2_MIGRATION_GUIDE.md
  auth0/src/main/java/com/auth0/android/Auth0.java
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.java
  auth0/src/main/java/com/auth0/android/provider/AlgorithmNameVerifier.java
  auth0/src/main/java/com/auth0/android/provider/OAuthManager.java
  auth0/src/main/java/com/auth0/android/provider/SignatureVerifier.java
  auth0/src/test/java/com/auth0/android/Auth0Test.java
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.java
  auth0/src/test/java/com/auth0/android/provider/AsymmetricSignatureVerifierTest.java
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.java
  sample/src/main/java/com/auth0/sample/DatabaseLoginFragment.kt
Labels: CH: Removed, review:large

#387 Remove support for Android WebView
  README.md
  V2_MIGRATION_GUIDE.md
  auth0/src/main/AndroidManifest.xml
  auth0/src/main/java/com/auth0/android/provider/AuthenticationActivity.java
  auth0/src/main/java/com/auth0/android/provider/OAuthManager.java
  auth0/src/main/java/com/auth0/android/provider/WebAuthActivity.java
  auth0/src/main/java/com/auth0/android/provider/WebAuthProvider.java
  auth0/src/main/res/layout/com_auth0_activity_web_auth.xml
  auth0/src/main/res/values/strings.xml
  auth0/src/test/AndroidManifest.xml
  auth0/src/test/java/com/auth0/android/provider/AuthenticationActivityTest.java
  auth0/src/test/java/com/auth0/android/provider/OAuthManagerTest.java
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.java
Labels: CH: Removed, review:medium

#351 Add custom headers to social token request [SDK-2080]
  auth0/src/main/java/com/auth0/android/provider/OAuthManager.java
  auth0/src/main/java/com/auth0/android/provider/PKCE.java
  auth0/src/main/java/com/auth0/android/provider/WebAuthProvider.java
  auth0/src/test/java/com/auth0/android/provider/PKCETest.java
Labels: waiting for customer

#388 Remove legacy Authentication API endpoints
  V2_MIGRATION_GUIDE.md
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.java
  auth0/src/main/java/com/auth0/android/authentication/ParameterBuilder.java
  auth0/src/main/java/com/auth0/android/authentication/request/DelegationRequest.java
  auth0/src/main/java/com/auth0/android/authentication/request/SignUpRequest.java
  auth0/src/main/java/com/auth0/android/request/AuthenticationRequest.java
  auth0/src/main/java/com/auth0/android/request/internal/BaseAuthenticationRequest.java
  auth0/src/main/java/com/auth0/android/result/Delegation.java
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.java
  auth0/src/test/java/com/auth0/android/authentication/request/AuthenticationRequestMock.java
  auth0/src/test/java/com/auth0/android/authentication/request/DelegationRequestTest.java
  auth0/src/test/java/com/auth0/android/authentication/request/SignUpRequestTest.java
  auth0/src/test/java/com/auth0/android/request/internal/BaseAuthenticationRequestTest.java
  auth0/src/test/java/com/auth0/android/result/DelegationTest.java
  auth0/src/test/java/com/auth0/android/util/AuthenticationAPI.java
Labels: CH: Removed

#391 Deprecate Legacy Authentication APIs
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.java
  auth0/src/main/java/com/auth0/android/authentication/ParameterBuilder.java
  auth0/src/main/java/com/auth0/android/authentication/request/DelegationRequest.java
  auth0/src/main/java/com/auth0/android/authentication/request/SignUpRequest.java
  auth0/src/main/java/com/auth0/android/request/AuthenticationRequest.java
  auth0/src/main/java/com/auth0/android/request/internal/BaseAuthenticationRequest.java
  auth0/src/main/java/com/auth0/android/result/Delegation.java
Labels: CH: Deprecated, review:medium

#392 Deprecate AuthorizableRequest
  auth0/src/main/java/com/auth0/android/request/AuthorizableRequest.java
Labels: CH: Deprecated, review:small

#393 Deprecate API client constructors that take Context
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.java
  auth0/src/main/java/com/auth0/android/management/UsersAPIClient.java
Labels: CH: Deprecated, review:tiny

#394 Release 1.30.0
  CHANGELOG.md
  README.md
Labels: review:tiny

#389 Always use Authorization Code + PKCE
  README.md
  V2_MIGRATION_GUIDE.md
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationException.java
  auth0/src/main/java/com/auth0/android/provider/AlgorithmHelper.java
  auth0/src/main/java/com/auth0/android/provider/OAuthManager.java
  auth0/src/main/java/com/auth0/android/provider/PKCE.java
  auth0/src/main/java/com/auth0/android/provider/WebAuthProvider.java
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationExceptionTest.java
  auth0/src/test/java/com/auth0/android/provider/OAuthManagerTest.java
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.java
Labels: CH: Removed, review:medium

#395 Add missing changelog entry
  CHANGELOG.md
Labels: review:tiny

#396 Remove AuthorizableRequest interface
  V2_MIGRATION_GUIDE.md
  auth0/src/main/java/com/auth0/android/request/AuthorizableRequest.java
  auth0/src/main/java/com/auth0/android/request/internal/BaseRequest.java
  auth0/src/test/java/com/auth0/android/request/internal/BaseRequestTest.java
Labels: CH: Removed, review:small

#398 Rename Telemetry class and its usage
  V2_MIGRATION_GUIDE.md
  auth0/src/main/java/com/auth0/android/Auth0.java
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.java
  auth0/src/main/java/com/auth0/android/management/UsersAPIClient.java
  auth0/src/main/java/com/auth0/android/provider/LogoutManager.java
  auth0/src/main/java/com/auth0/android/provider/OAuthManager.java
  auth0/src/main/java/com/auth0/android/request/internal/RequestFactory.java
  auth0/src/main/java/com/auth0/android/util/Auth0UserAgent.java
  auth0/src/test/java/com/auth0/android/Auth0Test.java
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.java
  auth0/src/test/java/com/auth0/android/management/UsersAPIClientTest.java
  auth0/src/test/java/com/auth0/android/util/Auth0UserAgentTest.java
Labels: CH: Breaking Change, medium

#399 Organize the introduced classes into better fit packages
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.java
  auth0/src/main/java/com/auth0/android/management/UsersAPIClient.java
  auth0/src/main/java/com/auth0/android/request/DefaultClient.kt
  auth0/src/main/java/com/auth0/android/request/ErrorAdapter.kt
  auth0/src/main/java/com/auth0/android/request/HttpMethod.kt
  auth0/src/main/java/com/auth0/android/request/JsonAdapter.kt
  auth0/src/main/java/com/auth0/android/request/NetworkingClient.kt
  auth0/src/main/java/com/auth0/android/request/RequestOptions.kt
  auth0/src/main/java/com/auth0/android/request/ServerResponse.kt
  auth0/src/main/java/com/auth0/android/request/internal/BaseRequest.kt
  auth0/src/main/java/com/auth0/android/request/internal/GsonAdapter.kt
  auth0/src/main/java/com/auth0/android/request/internal/OkClient.kt
  auth0/src/main/java/com/auth0/android/request/internal/RequestFactory.kt
  auth0/src/main/java/com/auth0/android/request/internal/ThreadUtils.kt
  auth0/src/main/java/com/auth0/android/request/internal/VoidRequest.java
  auth0/src/main/java/com/auth0/android/request/kt/ErrorBuilder.kt
  auth0/src/main/java/com/auth0/android/request/kt/JsonAdapter.kt
  auth0/src/main/java/com/auth0/android/request/kt/ServerResponse.kt
  auth0/src/test/java/com/auth0/android/request/internal/BaseAuthenticationRequestTest.java
  auth0/src/test/java/com/auth0/android/request/internal/BaseRequestTest.java
  auth0/src/test/java/com/auth0/android/request/internal/RequestFactoryTest.java
  auth0/src/test/java/com/auth0/android/request/kt/DefaultClientTest.kt
Labels: review:small

#404 Add ThreadSwitcher to execute requests asynchronously [SDK-2209]
  auth0/src/main/java/com/auth0/android/request/internal/BaseRequest.kt
  auth0/src/main/java/com/auth0/android/request/internal/RequestFactory.kt
  auth0/src/main/java/com/auth0/android/request/internal/ThreadSwitcher.kt
  auth0/src/main/java/com/auth0/android/request/internal/ThreadUtils.kt
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.java
  auth0/src/test/java/com/auth0/android/management/UsersAPIClientTest.java
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.java
  auth0/src/test/java/com/auth0/android/request/internal/BaseRequestTest.java
  auth0/src/test/java/com/auth0/android/request/internal/RequestFactoryTest.java
  auth0/src/test/java/com/auth0/android/request/internal/ThreadSwitcherShadow.java
  sample/src/main/java/com/auth0/sample/DatabaseLoginFragment.kt
Labels: medium

#401 Allow to set a custom networking client instance [SDK-2214]
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.java
  auth0/src/main/java/com/auth0/android/management/UsersAPIClient.java
  auth0/src/main/java/com/auth0/android/provider/OAuthManager.java
  auth0/src/main/java/com/auth0/android/provider/WebAuthProvider.java
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.java
  auth0/src/test/java/com/auth0/android/management/UsersAPIClientTest.java
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.java
Labels: medium

#405 Remove doNotSendTelemetry method
  V2_MIGRATION_GUIDE.md
  auth0/src/main/java/com/auth0/android/Auth0.java
  auth0/src/main/java/com/auth0/android/util/Auth0UserAgent.java
  auth0/src/test/java/com/auth0/android/Auth0Test.java
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.java
  auth0/src/test/java/com/auth0/android/management/UsersAPIClientTest.java
  auth0/src/test/java/com/auth0/android/util/Auth0UserAgentTest.java
Labels: CH: Removed, review:medium

#406 Networking stack refactor [SDK-2124]
  V2_MIGRATION_GUIDE.md
  auth0/build.gradle
  auth0/src/main/java/com/auth0/android/Auth0.java
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.java
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationException.java
  auth0/src/main/java/com/auth0/android/authentication/ParameterBuilder.java
  auth0/src/main/java/com/auth0/android/authentication/request/DatabaseConnectionRequest.java
  auth0/src/main/java/com/auth0/android/authentication/request/ProfileRequest.java
  auth0/src/main/java/com/auth0/android/authentication/request/SignUpRequest.java
  auth0/src/main/java/com/auth0/android/callback/BaseCallback.java
  auth0/src/main/java/com/auth0/android/management/UsersAPIClient.java
  auth0/src/main/java/com/auth0/android/provider/OAuthManager.java
  auth0/src/main/java/com/auth0/android/provider/WebAuthProvider.java
  auth0/src/main/java/com/auth0/android/request/AuthenticationRequest.java
  auth0/src/main/java/com/auth0/android/request/DefaultClient.kt
  auth0/src/main/java/com/auth0/android/request/ErrorAdapter.kt
  auth0/src/main/java/com/auth0/android/request/HttpMethod.kt
  auth0/src/main/java/com/auth0/android/request/JsonAdapter.kt
  auth0/src/main/java/com/auth0/android/request/NetworkingClient.kt
  auth0/src/main/java/com/auth0/android/request/Request.java
  auth0/src/main/java/com/auth0/android/request/RequestOptions.kt
  auth0/src/main/java/com/auth0/android/request/ServerResponse.kt
  auth0/src/main/java/com/auth0/android/request/internal/AwareInputStreamReader.kt
  auth0/src/main/java/com/auth0/android/request/internal/BaseAuthenticationRequest.java
  auth0/src/main/java/com/auth0/android/request/internal/BaseRequest.java
  auth0/src/main/java/com/auth0/android/request/internal/BaseRequest.kt
  auth0/src/main/java/com/auth0/android/request/internal/GsonAdapter.kt
  auth0/src/main/java/com/auth0/android/request/internal/OkClient.kt
  auth0/src/main/java/com/auth0/android/request/internal/RequestFactory.java
  auth0/src/main/java/com/auth0/android/request/internal/RequestFactory.kt
  auth0/src/main/java/com/auth0/android/request/internal/SimpleRequest.java
  auth0/src/main/java/com/auth0/android/request/internal/ThreadSwitcher.kt
  auth0/src/main/java/com/auth0/android/request/internal/VoidRequest.java
  auth0/src/test/java/com/auth0/android/Auth0Test.java
  auth0/src/test/java/com/auth0/android/MockAuth0.java
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.java
  auth0/src/test/java/com/auth0/android/authentication/ParameterBuilderTest.java
  auth0/src/test/java/com/auth0/android/authentication/request/AuthenticationRequestMock.java
  auth0/src/test/java/com/auth0/android/authentication/request/ProfileRequestTest.java
  auth0/src/test/java/com/auth0/android/authentication/request/RequestMock.java
  auth0/src/test/java/com/auth0/android/authentication/request/SignUpRequestTest.java
  auth0/src/test/java/com/auth0/android/authentication/storage/CryptoUtilTest.java
  auth0/src/test/java/com/auth0/android/management/UsersAPIClientTest.java
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.java
  auth0/src/test/java/com/auth0/android/request/internal/AuthenticationRequestMatcher.java
  auth0/src/test/java/com/auth0/android/request/internal/BaseAuthenticationRequestTest.java
  auth0/src/test/java/com/auth0/android/request/internal/BaseRequestTest.java
  auth0/src/test/java/com/auth0/android/request/internal/MockAuthenticationRequest.java
  auth0/src/test/java/com/auth0/android/request/internal/MockRequest.java
  auth0/src/test/java/com/auth0/android/request/internal/RequestFactoryTest.java
  auth0/src/test/java/com/auth0/android/request/internal/RequestMatcher.java
  auth0/src/test/java/com/auth0/android/request/internal/SimpleRequestTest.java
  auth0/src/test/java/com/auth0/android/request/internal/ThreadSwitcherShadow.java
  auth0/src/test/java/com/auth0/android/request/kt/DefaultClientTest.kt
  auth0/src/test/java/com/auth0/android/util/AuthenticationCallbackMatcher.java
  auth0/src/test/java/com/auth0/android/util/ManagementCallbackMatcher.java
  auth0/src/test/resources/org/powermock/extensions/configuration.properties
  build.gradle
  sample/src/main/java/com/auth0/sample/DatabaseLoginFragment.kt
Labels: CH: Breaking Change

#407 Pull latest release changes into v2
  CHANGELOG.md
  README.md
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.java
  auth0/src/main/java/com/auth0/android/authentication/ParameterBuilder.java
  auth0/src/main/java/com/auth0/android/management/UsersAPIClient.java
  auth0/src/main/java/com/auth0/android/provider/OAuthManager.java
  auth0/src/main/java/com/auth0/android/provider/PKCE.java
  auth0/src/main/java/com/auth0/android/provider/WebAuthProvider.java
  auth0/src/main/java/com/auth0/android/request/AuthenticationRequest.java
  auth0/src/test/java/com/auth0/android/provider/PKCETest.java
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.java
Labels: medium

#409 Update Robolectric to 4.4
  .circleci/config.yml
  auth0/build.gradle
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.java
  auth0/src/test/java/com/auth0/android/management/UsersAPIClientTest.java
  auth0/src/test/java/com/auth0/android/provider/RedirectActivityShadow.java
  auth0/src/test/java/com/auth0/android/provider/RedirectActivityTest.java
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.java
  auth0/src/test/java/com/auth0/android/request/internal/BaseRequestTest.java
  auth0/src/test/java/com/auth0/android/request/internal/ThreadSwitcherShadow.java
  sample/build.gradle
Labels: review:medium

#408 Remove deprecated methods from v1
  V2_MIGRATION_GUIDE.md
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.java
  auth0/src/main/java/com/auth0/android/authentication/ParameterBuilder.java
  auth0/src/main/java/com/auth0/android/authentication/request/SignUpRequest.java
  auth0/src/main/java/com/auth0/android/callback/BaseCallback.java
  auth0/src/main/java/com/auth0/android/management/UsersAPIClient.java
  auth0/src/main/java/com/auth0/android/provider/ResponseType.java
  auth0/src/main/java/com/auth0/android/request/AuthenticationRequest.java
  auth0/src/main/java/com/auth0/android/request/internal/AuthenticationErrorBuilder.java
  auth0/src/main/java/com/auth0/android/request/internal/BaseAuthenticationRequest.java
  auth0/src/main/java/com/auth0/android/request/internal/JsonRequestBodyBuilder.java
  auth0/src/main/java/com/auth0/android/request/internal/ManagementErrorBuilder.java
  auth0/src/main/java/com/auth0/android/request/internal/OkClient.kt
  auth0/src/main/java/com/auth0/android/request/internal/VoidRequest.java
  auth0/src/main/java/com/auth0/android/result/Credentials.java
  auth0/src/test/java/com/auth0/android/MockAuth0.java
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.java
  auth0/src/test/java/com/auth0/android/authentication/ParameterBuilderTest.java
  auth0/src/test/java/com/auth0/android/authentication/request/AuthenticationRequestMock.java
  auth0/src/test/java/com/auth0/android/authentication/request/SignUpRequestTest.java
  auth0/src/test/java/com/auth0/android/authentication/storage/CredentialsManagerTest.java
  auth0/src/test/java/com/auth0/android/management/UsersAPIClientTest.java
  auth0/src/test/java/com/auth0/android/request/internal/AuthenticationErrorBuilderTest.java
  auth0/src/test/java/com/auth0/android/request/internal/BaseAuthenticationRequestTest.java
  auth0/src/test/java/com/auth0/android/request/internal/ManagementErrorBuilderTest.java
Labels: CH: Removed, medium
