Repository auth0/Auth0.Android, pull requests merged in 2021-02, with the labels that each got.

#450 Reformat FAQ answers as headings in the readme
  README.md
Labels: documentation, review:tiny

#452 Make JsonRequired annotation internal
  V2_MIGRATION_GUIDE.md
  auth0/src/main/java/com/auth0/android/request/internal/GsonProvider.kt
  auth0/src/main/java/com/auth0/android/request/internal/JsonRequired.kt
  auth0/src/main/java/com/auth0/android/request/internal/JsonRequiredTypeAdapterFactory.java
  auth0/src/main/java/com/auth0/android/result/DatabaseUser.kt
  auth0/src/main/java/com/auth0/android/result/UserIdentity.kt
  auth0/src/main/java/com/auth0/android/util/JsonRequired.java
  auth0/src/test/java/com/auth0/android/request/internal/JsonRequiredTypeAdapterFactoryTest.java
  auth0/src/test/java/com/auth0/android/result/JsonRequiredTypeAdapterFactoryTest.java
Labels: medium

#451 Execute MockWebServer tests with HTTPS
  auth0/build.gradle
  auth0/src/main/java/com/auth0/android/Auth0.kt
  auth0/src/main/java/com/auth0/android/request/DefaultClient.kt
  auth0/src/test/java/com/auth0/android/MockAuth0.kt
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.java
  auth0/src/test/java/com/auth0/android/management/UsersAPIClientTest.java
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.kt
  auth0/src/test/java/com/auth0/android/request/DefaultClientTest.kt
  auth0/src/test/java/com/auth0/android/util/AuthenticationAPI.java
  auth0/src/test/java/com/auth0/android/util/AuthenticationAPIMockServer.kt
  auth0/src/test/java/com/auth0/android/util/SSLTestUtils.kt
  auth0/src/test/java/com/auth0/android/util/UsersAPI.java
  auth0/src/test/java/com/auth0/android/util/UsersAPIMockServer.kt
Labels: large

#453 Convert API Client Tests to Kotlin
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.java
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.kt
  auth0/src/test/java/com/auth0/android/management/UsersAPIClientTest.java
  auth0/src/test/java/com/auth0/android/management/UsersAPIClientTest.kt
  auth0/src/test/java/com/auth0/android/util/SSLTestUtils.kt
Labels: medium

#454 Extract common API Client Mock Server Class
  auth0/src/test/java/com/auth0/android/util/APIMockServer.kt
  auth0/src/test/java/com/auth0/android/util/AuthenticationAPIMockServer.kt
  auth0/src/test/java/com/auth0/android/util/UsersAPIMockServer.kt
Labels: review:medium

#455 Enforce openid scope on the AuthenticationAPIClient
  README.md
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.kt
  auth0/src/main/java/com/auth0/android/authentication/ParameterBuilder.kt
  auth0/src/main/java/com/auth0/android/provider/OAuthManager.kt
  auth0/src/main/java/com/auth0/android/request/internal/BaseRequest.kt
  auth0/src/main/java/com/auth0/android/request/internal/OidcUtils.kt
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.kt
  auth0/src/test/java/com/auth0/android/authentication/ParameterBuilderTest.java
  auth0/src/test/java/com/auth0/android/request/internal/BaseAuthenticationRequestTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/BaseRequestTest.kt
Labels: CH: Changed, medium

#456 Use dokka for docs generation
  auth0/build.gradle
Labels: review:small

#457 Improve Credentials class nullability
  auth0/src/main/java/com/auth0/android/authentication/storage/BaseCredentialsManager.kt
  auth0/src/main/java/com/auth0/android/authentication/storage/CredentialsManager.kt
  auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.kt
  auth0/src/main/java/com/auth0/android/result/Credentials.kt
  auth0/src/main/java/com/auth0/android/result/OptionalCredentials.kt
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.kt
  auth0/src/test/java/com/auth0/android/authentication/storage/CredentialsManagerTest.kt
  auth0/src/test/java/com/auth0/android/authentication/storage/SecureCredentialsManagerTest.kt
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/CredentialsDeserializerTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/CredentialsGsonTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/OptionalCredentialsGsonTest.kt
  auth0/src/test/java/com/auth0/android/result/CredentialsMock.kt
  auth0/src/test/java/com/auth0/android/util/AuthenticationAPIMockServer.kt
  auth0/src/test/resources/credentials_legacy.json
  auth0/src/test/resources/credentials_legacy_expires_at.json
  auth0/src/test/resources/credentials_openid.json
Labels: CH: Changed, medium

#458 Release 2.0.0
  CHANGELOG.md
  README.md
Labels: review:tiny

#460 Add SLA to v1 README
  README.md
Labels: tiny
