Repository auth0/Auth0.Android, pull requests merged in 2021-01, with the labels that each got.

#411 Make callback interfaces take non-null arguments
  auth0/src/main/java/com/auth0/android/authentication/request/ProfileRequest.kt
  auth0/src/main/java/com/auth0/android/authentication/request/SignUpRequest.kt
  auth0/src/main/java/com/auth0/android/authentication/storage/CredentialsManager.kt
  auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.kt
  auth0/src/main/java/com/auth0/android/callback/BaseCallback.kt
  auth0/src/main/java/com/auth0/android/provider/LogoutManager.kt
  auth0/src/main/java/com/auth0/android/provider/OAuthManager.kt
  auth0/src/test/java/com/auth0/android/provider/LogoutManagerTest.java
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.kt
  sample/src/main/java/com/auth0/sample/DatabaseLoginFragment.kt
Labels: CH: Changed, small

#413 Revert "Make callback interfaces take non-null arguments"
  auth0/src/main/java/com/auth0/android/authentication/request/ProfileRequest.kt
  auth0/src/main/java/com/auth0/android/authentication/request/SignUpRequest.kt
  auth0/src/main/java/com/auth0/android/authentication/storage/CredentialsManager.kt
  auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.kt
  auth0/src/main/java/com/auth0/android/callback/BaseCallback.kt
  auth0/src/main/java/com/auth0/android/provider/LogoutManager.kt
  auth0/src/main/java/com/auth0/android/provider/OAuthManager.kt
  auth0/src/test/java/com/auth0/android/provider/LogoutManagerTest.java
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.kt
  sample/src/main/java/com/auth0/sample/DatabaseLoginFragment.kt
Labels: CH: Changed

#415 Change WebAuthProvider (Login) callback type
  README.md
  V2_MIGRATION_GUIDE.md
  auth0/src/main/java/com/auth0/android/provider/OAuthManager.kt
  auth0/src/main/java/com/auth0/android/provider/PKCE.java
  auth0/src/main/java/com/auth0/android/provider/SimpleAuthCallback.java
  auth0/src/main/java/com/auth0/android/provider/WebAuthProvider.kt
  auth0/src/test/java/com/auth0/android/provider/PKCETest.java
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.kt
Labels: CH: Breaking Change, medium

#414 Stop using kotlin.Unit in public APIs
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.kt
  auth0/src/main/java/com/auth0/android/authentication/request/DatabaseConnectionRequest.kt
  auth0/src/main/java/com/auth0/android/authentication/request/ProfileRequest.kt
  auth0/src/main/java/com/auth0/android/authentication/request/SignUpRequest.kt
  auth0/src/main/java/com/auth0/android/provider/OAuthManager.kt
  auth0/src/main/java/com/auth0/android/provider/VoidCallback.kt
  auth0/src/main/java/com/auth0/android/request/JsonAdapter.kt
  auth0/src/main/java/com/auth0/android/request/Request.kt
  auth0/src/main/java/com/auth0/android/request/internal/BaseAuthenticationRequest.kt
  auth0/src/main/java/com/auth0/android/request/internal/BaseRequest.kt
  auth0/src/main/java/com/auth0/android/request/internal/RequestFactory.kt
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.java
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/RequestFactoryTest.java
  auth0/src/test/java/com/auth0/android/util/AuthenticationCallbackMatcher.java
  auth0/src/test/java/com/auth0/android/util/ManagementCallbackMatcher.java
Labels: CH: Changed, medium

#416 Merge BaseCallback into Callback - [SDK-2185]
  README.md
  V2_MIGRATION_GUIDE.md
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.kt
  auth0/src/main/java/com/auth0/android/authentication/request/DatabaseConnectionRequest.kt
  auth0/src/main/java/com/auth0/android/authentication/request/ProfileRequest.kt
  auth0/src/main/java/com/auth0/android/authentication/request/SignUpRequest.kt
  auth0/src/main/java/com/auth0/android/authentication/storage/BaseCredentialsManager.kt
  auth0/src/main/java/com/auth0/android/authentication/storage/CredentialsManager.kt
  auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.kt
  auth0/src/main/java/com/auth0/android/callback/AuthenticationCallback.kt
  auth0/src/main/java/com/auth0/android/callback/BaseCallback.kt
  auth0/src/main/java/com/auth0/android/callback/Callback.kt
  auth0/src/main/java/com/auth0/android/callback/ManagementCallback.kt
  auth0/src/main/java/com/auth0/android/management/UsersAPIClient.kt
  auth0/src/main/java/com/auth0/android/provider/OAuthManager.kt
  auth0/src/main/java/com/auth0/android/provider/PKCE.java
  auth0/src/main/java/com/auth0/android/provider/SignatureVerifier.java
  auth0/src/main/java/com/auth0/android/provider/VoidCallback.kt
  auth0/src/main/java/com/auth0/android/provider/WebAuthProvider.kt
  auth0/src/main/java/com/auth0/android/request/Request.kt
  auth0/src/main/java/com/auth0/android/request/internal/BaseAuthenticationRequest.kt
  auth0/src/main/java/com/auth0/android/request/internal/BaseRequest.kt
  auth0/src/test/java/com/auth0/android/authentication/request/AuthenticationRequestMock.java
  auth0/src/test/java/com/auth0/android/authentication/request/DatabaseConnectionRequestMock.java
  auth0/src/test/java/com/auth0/android/authentication/request/DatabaseConnectionRequestTest.java
  auth0/src/test/java/com/auth0/android/authentication/request/ProfileRequestTest.java
  auth0/src/test/java/com/auth0/android/authentication/request/RequestMock.java
  auth0/src/test/java/com/auth0/android/authentication/request/SignUpRequestTest.java
  auth0/src/test/java/com/auth0/android/authentication/storage/CredentialsManagerTest.kt
  auth0/src/test/java/com/auth0/android/authentication/storage/SecureCredentialsManagerTest.kt
  auth0/src/test/java/com/auth0/android/provider/PKCETest.java
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/BaseRequestTest.java
  auth0/src/test/java/com/auth0/android/request/internal/MockAuthenticationRequest.java
  auth0/src/test/java/com/auth0/android/request/internal/MockRequest.java
  auth0/src/test/java/com/auth0/android/util/CallbackMatcher.java
  auth0/src/test/java/com/auth0/android/util/MockCallback.java
Labels: CH: Deprecated

#417 Remove DatabaseConnectionRequest class
  V2_MIGRATION_GUIDE.md
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.kt
  auth0/src/main/java/com/auth0/android/authentication/request/DatabaseConnectionRequest.kt
  auth0/src/main/java/com/auth0/android/authentication/request/SignUpRequest.kt
  auth0/src/test/java/com/auth0/android/authentication/request/DatabaseConnectionRequestMock.java
  auth0/src/test/java/com/auth0/android/authentication/request/DatabaseConnectionRequestTest.java
  auth0/src/test/java/com/auth0/android/authentication/request/SignUpRequestTest.java
Labels: CH: Removed, medium

#418 Update API docs
  auth0/src/main/java/com/auth0/android/Auth0.kt
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.kt
  auth0/src/main/java/com/auth0/android/authentication/ParameterBuilder.kt
  auth0/src/main/java/com/auth0/android/authentication/request/SignUpRequest.kt
  auth0/src/main/java/com/auth0/android/management/UsersAPIClient.kt
Labels: documentation

#419 Fix API docs typos
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.kt
  auth0/src/main/java/com/auth0/android/management/UsersAPIClient.kt
Labels: documentation, review:small

#420 Update readme in preparation of v2
  README.md
Labels: CH: Changed, medium

#421 Update WebAuthProvider#start required Context
  auth0/src/main/java/com/auth0/android/provider/OAuthManager.kt
  auth0/src/main/java/com/auth0/android/provider/WebAuthProvider.kt
  auth0/src/test/java/com/auth0/android/provider/OAuthManagerTest.java
Labels: CH: Changed, review:small

#424 Stop using VoidCallback on WebAuth Logout
  V2_MIGRATION_GUIDE.md
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationException.kt
  auth0/src/main/java/com/auth0/android/provider/LogoutManager.kt
  auth0/src/main/java/com/auth0/android/provider/OAuthManager.kt
  auth0/src/main/java/com/auth0/android/provider/WebAuthProvider.kt
  auth0/src/test/java/com/auth0/android/provider/LogoutManagerTest.java
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.kt
Labels: CH: Breaking Change, medium

#425 Deprecate isAuthenticationCanceled in favor of isCanceled
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationException.kt
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationExceptionTest.kt
Labels: CH: Deprecated, review:medium

#422 Enforce the "openid" scope for the WebAuthProvider
  README.md
  auth0/src/main/java/com/auth0/android/provider/OAuthManager.kt
  auth0/src/main/java/com/auth0/android/provider/WebAuthProvider.kt
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.kt
Labels: CH: Changed, review:small

#423 Update v2 Migration Guide
  V2_MIGRATION_GUIDE.md
Labels: documentation, medium

#426 Fix migration guide typo
  V2_MIGRATION_GUIDE.md
Labels: documentation, review:tiny

#428 Migrate default NetworkingClient implementation to use OkHttp
  auth0/build.gradle
  auth0/src/main/java/com/auth0/android/Auth0.kt
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.kt
  auth0/src/main/java/com/auth0/android/management/UsersAPIClient.kt
  auth0/src/main/java/com/auth0/android/request/DefaultClient.kt
  auth0/src/main/java/com/auth0/android/request/NetworkingClient.kt
  auth0/src/main/java/com/auth0/android/request/internal/OkClient.kt
  auth0/src/main/java/com/auth0/android/request/internal/OkHttpClientFactory.java
  auth0/src/test/java/com/auth0/android/Auth0Test.java
  auth0/src/test/java/com/auth0/android/MockAuth0.kt
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.java
  auth0/src/test/java/com/auth0/android/management/UsersAPIClientTest.java
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.kt
  auth0/src/test/java/com/auth0/android/request/DefaultClientTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/AuthenticationRequestMatcher.java
  auth0/src/test/java/com/auth0/android/request/internal/OkHttpClientFactoryTest.java
  auth0/src/test/java/com/auth0/android/request/internal/RequestMatcher.java
  auth0/src/test/java/com/auth0/android/request/internal/ResponseUtilsTest.java
  auth0/src/test/java/com/auth0/android/util/AuthenticationAPI.java
  auth0/src/test/java/com/auth0/android/util/HttpUrlMatcher.java
  auth0/src/test/java/com/auth0/android/util/UsersAPI.java
Labels: CH: Changed, medium

#429 Fix request to patch user metadata
  auth0/src/main/java/com/auth0/android/management/UsersAPIClient.kt
  auth0/src/main/java/com/auth0/android/request/DefaultClient.kt
  auth0/src/main/java/com/auth0/android/request/RequestOptions.kt
  auth0/src/main/java/com/auth0/android/request/internal/BaseRequest.kt
  auth0/src/test/java/com/auth0/android/management/UsersAPIClientTest.java
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/BaseAuthenticationRequestTest.java
  auth0/src/test/java/com/auth0/android/request/internal/BaseRequestTest.java
Labels: CH: Fixed, medium

#431 Deprecate timeout logging config on Auth0
  auth0/src/main/java/com/auth0/android/Auth0.kt
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.kt
  auth0/src/main/java/com/auth0/android/management/UsersAPIClient.kt
Labels: CH: Deprecated, review:small

#433 Move to a JSON client singleton
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.kt
  auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.kt
  auth0/src/main/java/com/auth0/android/management/UsersAPIClient.kt
  auth0/src/main/java/com/auth0/android/request/DefaultClient.kt
  auth0/src/main/java/com/auth0/android/request/internal/GsonAdapter.kt
  auth0/src/main/java/com/auth0/android/request/internal/GsonProvider.java
  auth0/src/main/java/com/auth0/android/request/internal/GsonProvider.kt
  auth0/src/main/java/com/auth0/android/request/internal/JwksDeserializer.java
  auth0/src/main/java/com/auth0/android/request/internal/JwksDeserializer.kt
  auth0/src/main/java/com/auth0/android/util/Auth0UserAgent.kt
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationExceptionTest.kt
  auth0/src/test/java/com/auth0/android/authentication/storage/SecureCredentialsManagerTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/BaseAuthenticationRequestTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/BaseRequestTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/CredentialsDeserializerTest.java
  auth0/src/test/java/com/auth0/android/request/internal/CredentialsDeserializerTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/CredentialsGsonTest.java
  auth0/src/test/java/com/auth0/android/request/internal/CredentialsGsonTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/GsonBaseTest.java
  auth0/src/test/java/com/auth0/android/request/internal/GsonBaseTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/JwksGsonTest.java
  auth0/src/test/java/com/auth0/android/request/internal/JwksGsonTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/UserIdentityGsonTest.java
  auth0/src/test/java/com/auth0/android/request/internal/UserIdentityGsonTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/UserProfileGsonTest.java
  auth0/src/test/java/com/auth0/android/request/internal/UserProfileGsonTest.kt
Labels: CH: Changed, medium

#432 Remove obsolete config properties
  V2_MIGRATION_GUIDE.md
  auth0/src/main/java/com/auth0/android/Auth0.kt
  auth0/src/test/java/com/auth0/android/Auth0Test.java
Labels: CH: Removed, review:small

#434 Fix auth0UserAgent property definition
  auth0/src/main/java/com/auth0/android/Auth0.kt
Labels: review:tiny

#438 Fix JavaDocs Typo on RS256 Verifier
  auth0/src/main/java/com/auth0/android/provider/AsymmetricSignatureVerifier.java
Labels: documentation

#437 Update licenses
  LICENSE
  auth0/src/main/AndroidManifest.xml
  auth0/src/main/java/com/auth0/android/Auth0.kt
  auth0/src/main/java/com/auth0/android/Auth0Exception.kt
  auth0/src/main/java/com/auth0/android/RequestBodyBuildException.kt
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.kt
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationException.kt
  auth0/src/main/java/com/auth0/android/authentication/ParameterBuilder.kt
  auth0/src/main/java/com/auth0/android/authentication/PasswordlessType.java
  auth0/src/main/java/com/auth0/android/callback/BaseCallback.kt
  auth0/src/main/java/com/auth0/android/callback/Callback.kt
  auth0/src/main/java/com/auth0/android/management/ManagementException.kt
  auth0/src/main/java/com/auth0/android/management/UsersAPIClient.kt
  auth0/src/main/java/com/auth0/android/provider/AuthCallback.kt
  auth0/src/main/java/com/auth0/android/provider/AuthProvider.java
  auth0/src/main/java/com/auth0/android/provider/AuthorizeResult.java
  auth0/src/main/java/com/auth0/android/provider/CallbackHelper.java
  auth0/src/main/java/com/auth0/android/provider/PKCE.java
  auth0/src/main/java/com/auth0/android/provider/PermissionHandler.java
  auth0/src/main/java/com/auth0/android/provider/VoidCallback.kt
  auth0/src/main/java/com/auth0/android/provider/WebAuthProvider.kt
  auth0/src/main/java/com/auth0/android/request/ProfileRequest.kt
  auth0/src/main/java/com/auth0/android/request/Request.kt
  auth0/src/main/java/com/auth0/android/request/SignUpRequest.kt
  auth0/src/main/java/com/auth0/android/request/internal/BaseRequest.kt
  auth0/src/main/java/com/auth0/android/request/internal/RequestFactory.kt
  auth0/src/main/java/com/auth0/android/result/Authentication.kt
  auth0/src/main/java/com/auth0/android/result/Credentials.kt
  auth0/src/main/java/com/auth0/android/result/DatabaseUser.kt
  auth0/src/main/java/com/auth0/android/result/UserIdentity.kt
  auth0/src/main/java/com/auth0/android/result/UserProfile.kt
  auth0/src/main/java/com/auth0/android/util/CheckHelper.java
  auth0/src/main/java/com/auth0/android/util/JsonRequired.java
  auth0/src/main/res/values/strings.xml
  auth0/src/test/AndroidManifest.xml
  auth0/src/test/java/com/auth0/android/Auth0Test.java
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.java
  auth0/src/test/java/com/auth0/android/authentication/ParameterBuilderTest.java
  auth0/src/test/java/com/auth0/android/management/UsersAPIClientTest.java
  auth0/src/test/java/com/auth0/android/provider/AuthProviderTest.java
  auth0/src/test/java/com/auth0/android/provider/AuthorizeResultTest.java
  auth0/src/test/java/com/auth0/android/provider/CallbackHelperTest.java
  auth0/src/test/java/com/auth0/android/provider/PKCETest.java
  auth0/src/test/java/com/auth0/android/request/internal/BaseRequestTest.kt
  auth0/src/test/java/com/auth0/android/util/AuthCallbackMatcher.java
  auth0/src/test/java/com/auth0/android/util/AuthenticationAPI.java
  auth0/src/test/java/com/auth0/android/util/AuthenticationCallbackMatcher.java
  auth0/src/test/java/com/auth0/android/util/CallbackMatcher.java
  auth0/src/test/java/com/auth0/android/util/ManagementCallbackMatcher.java
  auth0/src/test/java/com/auth0/android/util/MockAuthCallback.java
  auth0/src/test/java/com/auth0/android/util/MockAuthenticationCallback.java
  auth0/src/test/java/com/auth0/android/util/MockCallback.java
  auth0/src/test/java/com/auth0/android/util/MockManagementCallback.java
  auth0/src/test/java/com/auth0/android/util/UsersAPI.java
Labels: documentation

#435 Update the Credentials class
  V2_MIGRATION_GUIDE.md
  auth0/src/main/java/com/auth0/android/result/Credentials.kt
  auth0/src/test/java/com/auth0/android/authentication/storage/CredentialsManagerTest.kt
  auth0/src/test/java/com/auth0/android/authentication/storage/SecureCredentialsManagerTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/CredentialsDeserializerTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/CredentialsGsonTest.kt
  auth0/src/test/java/com/auth0/android/result/CredentialsMock.kt
  auth0/src/test/java/com/auth0/android/result/CredentialsTest.java
Labels: CH: Changed, medium

#439 Run and fix inspections, remove unused classes
  V2_MIGRATION_GUIDE.md
  auth0/build.gradle
  auth0/src/main/java/com/auth0/android/Auth0.kt
  auth0/src/main/java/com/auth0/android/RequestBodyBuildException.kt
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationException.kt
  auth0/src/main/java/com/auth0/android/authentication/storage/BaseCredentialsManager.kt
  auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.kt
  auth0/src/main/java/com/auth0/android/authentication/storage/SharedPreferencesStorage.kt
  auth0/src/main/java/com/auth0/android/provider/AuthProvider.java
  auth0/src/main/java/com/auth0/android/provider/CustomTabsController.java
  auth0/src/main/java/com/auth0/android/provider/LogoutManager.kt
  auth0/src/main/java/com/auth0/android/provider/OAuthManager.kt
  auth0/src/main/java/com/auth0/android/provider/WebAuthProvider.kt
  auth0/src/main/java/com/auth0/android/request/ErrorBuilder.java
  auth0/src/main/java/com/auth0/android/request/ProfileRequest.kt
  auth0/src/main/java/com/auth0/android/result/Authentication.kt
  auth0/src/main/java/com/auth0/android/result/DatabaseUser.kt
  auth0/src/main/java/com/auth0/android/util/CheckHelper.java
Labels: CH: Changed, medium

#440 Receive NetworkingClient through the Auth0 instance
  auth0/src/main/java/com/auth0/android/Auth0.kt
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.kt
  auth0/src/main/java/com/auth0/android/management/UsersAPIClient.kt
  auth0/src/main/java/com/auth0/android/provider/OAuthManager.kt
  auth0/src/main/java/com/auth0/android/provider/WebAuthProvider.kt
  auth0/src/main/java/com/auth0/android/request/internal/RequestFactory.kt
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.java
  auth0/src/test/java/com/auth0/android/management/UsersAPIClientTest.java
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/RequestFactoryTest.java
Labels: CH: Changed, small

#441 Remove timeouts and logging setters from Auth0 class
  V2_MIGRATION_GUIDE.md
  auth0/src/main/java/com/auth0/android/Auth0.kt
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.kt
  auth0/src/main/java/com/auth0/android/management/UsersAPIClient.kt
  auth0/src/main/java/com/auth0/android/provider/LogoutManager.kt
  auth0/src/main/java/com/auth0/android/provider/OAuthManager.kt
  auth0/src/test/java/com/auth0/android/Auth0Test.java
  sample/src/main/java/com/auth0/sample/DatabaseLoginFragment.kt
  sample/src/main/res/layout/fragment_database_login.xml
Labels: CH: Removed, small

#436 Document Networking Client Configuration
  README.md
  V2_MIGRATION_GUIDE.md
Labels: documentation

#442 Explicitly reject "none" signing algorithm
  auth0/src/main/java/com/auth0/android/provider/SignatureVerifier.java
Labels: CH: Changed, tiny

#443 Refactor JWT decoding logic
  auth0/build.gradle
  auth0/src/main/java/com/auth0/android/authentication/storage/JWTDecoder.java
  auth0/src/main/java/com/auth0/android/provider/IdTokenVerifier.java
  auth0/src/main/java/com/auth0/android/provider/OAuthManager.kt
  auth0/src/main/java/com/auth0/android/provider/SignatureVerifier.java
  auth0/src/main/java/com/auth0/android/provider/TokenValidationException.kt
  auth0/src/main/java/com/auth0/android/request/internal/Jwt.kt
  auth0/src/test/java/com/auth0/android/authentication/storage/CredentialsManagerTest.kt
  auth0/src/test/java/com/auth0/android/authentication/storage/JWTDecoderTest.java
  auth0/src/test/java/com/auth0/android/authentication/storage/SecureCredentialsManagerTest.kt
  auth0/src/test/java/com/auth0/android/provider/AsymmetricSignatureVerifierTest.java
  auth0/src/test/java/com/auth0/android/provider/IdTokenVerifierTest.java
  auth0/src/test/java/com/auth0/android/request/internal/JwtTest.kt
  gradle.properties
Labels: CH: Changed, medium

#444 remove setUserAgent methods from API clients
  V2_MIGRATION_GUIDE.md
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.kt
  auth0/src/main/java/com/auth0/android/management/UsersAPIClient.kt
  auth0/src/main/java/com/auth0/android/request/internal/RequestFactory.kt
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.java
  auth0/src/test/java/com/auth0/android/management/UsersAPIClientTest.java
  auth0/src/test/java/com/auth0/android/request/internal/RequestFactoryTest.java
  sample/src/main/java/com/auth0/sample/DatabaseLoginFragment.kt
Labels: CH: Removed, review:small

#447 Make requests that return Void have an optional type
  README.md
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.kt
  auth0/src/main/java/com/auth0/android/authentication/storage/CredentialsManager.kt
  auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.kt
  auth0/src/main/java/com/auth0/android/callback/Callback.kt
  auth0/src/main/java/com/auth0/android/management/UsersAPIClient.kt
  auth0/src/main/java/com/auth0/android/provider/IdTokenVerifier.java
  auth0/src/main/java/com/auth0/android/provider/LogoutManager.kt
  auth0/src/main/java/com/auth0/android/provider/OAuthManager.kt
  auth0/src/main/java/com/auth0/android/provider/SignatureVerifier.java
  auth0/src/main/java/com/auth0/android/provider/VoidCallback.kt
  auth0/src/main/java/com/auth0/android/provider/WebAuthProvider.kt
  auth0/src/main/java/com/auth0/android/request/DefaultClient.kt
  auth0/src/main/java/com/auth0/android/request/JsonAdapter.kt
  auth0/src/main/java/com/auth0/android/request/ProfileRequest.kt
  auth0/src/main/java/com/auth0/android/request/Request.kt
  auth0/src/main/java/com/auth0/android/request/SignUpRequest.kt
  auth0/src/main/java/com/auth0/android/request/internal/BaseAuthenticationRequest.kt
  auth0/src/main/java/com/auth0/android/request/internal/BaseRequest.kt
  auth0/src/main/java/com/auth0/android/request/internal/RequestFactory.kt
  auth0/src/test/java/com/auth0/android/authentication/storage/SharedPreferencesStorageTest.java
  auth0/src/test/java/com/auth0/android/provider/JwtTestUtils.java
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/BaseRequestTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/RequestFactoryTest.java
  auth0/src/test/java/com/auth0/android/util/MockAuthenticationCallback.java
  auth0/src/test/java/com/auth0/android/util/MockCallback.java
  auth0/src/test/java/com/auth0/android/util/MockManagementCallback.java
  sample/src/main/java/com/auth0/sample/DatabaseLoginFragment.kt
Labels: CH: Changed, medium

#448 Run lint and fix inspection results
  auth0/src/main/java/com/auth0/android/management/ManagementException.kt
  auth0/src/main/java/com/auth0/android/provider/WebAuthProvider.kt
  auth0/src/main/java/com/auth0/android/request/internal/RequestFactory.kt
  auth0/src/test/java/com/auth0/android/Auth0Test.java
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.java
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationExceptionTest.kt
  auth0/src/test/java/com/auth0/android/authentication/ParameterBuilderTest.java
  auth0/src/test/java/com/auth0/android/authentication/request/AuthenticationRequestMock.java
  auth0/src/test/java/com/auth0/android/authentication/request/ProfileRequestTest.java
  auth0/src/test/java/com/auth0/android/authentication/request/RequestMock.java
  auth0/src/test/java/com/auth0/android/authentication/request/SignUpRequestTest.java
  auth0/src/test/java/com/auth0/android/authentication/storage/CryptoUtilTest.java
  auth0/src/test/java/com/auth0/android/authentication/storage/SecureCredentialsManagerTest.kt
  auth0/src/test/java/com/auth0/android/authentication/storage/SharedPreferencesStorageTest.java
  auth0/src/test/java/com/auth0/android/provider/AsymmetricSignatureVerifierTest.java
  auth0/src/test/java/com/auth0/android/provider/AuthProviderTest.java
  auth0/src/test/java/com/auth0/android/provider/AuthenticationActivityTest.kt
  auth0/src/test/java/com/auth0/android/provider/BrowserPickerTest.java
  auth0/src/test/java/com/auth0/android/provider/CallbackHelperTest.java
  auth0/src/test/java/com/auth0/android/provider/CustomTabsControllerTest.java
  auth0/src/test/java/com/auth0/android/provider/CustomTabsOptionsTest.java
  auth0/src/test/java/com/auth0/android/provider/IdTokenVerifierTest.java
  auth0/src/test/java/com/auth0/android/provider/LogoutManagerTest.java
  auth0/src/test/java/com/auth0/android/provider/OAuthManagerTest.java
  auth0/src/test/java/com/auth0/android/provider/PKCETest.java
  auth0/src/test/java/com/auth0/android/provider/RedirectActivityTest.java
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.kt
  auth0/src/test/java/com/auth0/android/request/DefaultClientTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/BaseRequestTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/JwtTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/MockRequest.java
  auth0/src/test/java/com/auth0/android/request/internal/RequestMatcher.java
  auth0/src/test/java/com/auth0/android/request/internal/ResponseUtilsTest.java
  auth0/src/test/java/com/auth0/android/request/internal/TLS12SocketFactoryTest.java
  auth0/src/test/java/com/auth0/android/request/internal/UserProfileGsonTest.kt
  auth0/src/test/java/com/auth0/android/util/Auth0UserAgentTest.java
  auth0/src/test/java/com/auth0/android/util/AuthenticationAPI.java
  auth0/src/test/java/com/auth0/android/util/MockAuthCallback.java
  auth0/src/test/java/com/auth0/android/util/MockAuthenticationCallback.java
  auth0/src/test/java/com/auth0/android/util/MockCallback.java
  auth0/src/test/java/com/auth0/android/util/MockManagementCallback.java
  auth0/src/test/java/com/auth0/android/util/UsersAPI.java
  build.gradle
  sample/build.gradle
  sample/src/main/res/layout/fragment_database_login.xml
  sample/src/main/res/values/strings.xml
Labels: large
