Repository auth0/Auth0.Android, pull requests merged in 2021-04, with the labels that each got.

#472 Improve docs around CredentialsManager concurrency
  README.md
Labels: review:small

#474 [SDK-2456] Remove Organizations Beta Labelling
  README.md
Labels: review:tiny

#475 Accept UserMetadata for creating users [SDK-2429]
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.kt
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.kt
Labels: CH: Added, medium

#476 Release 2.2.0
  CHANGELOG.md
  README.md
Labels: review:tiny
