Repository auth0/Auth0.Android, pull requests merged in 2021-09, with the labels that each got.

#492 Always close request body InputStream when exception occurs
  .circleci/config.yml
  auth0/src/main/java/com/auth0/android/request/internal/AwareInputStreamReader.kt
  auth0/src/main/java/com/auth0/android/request/internal/BaseRequest.kt
  auth0/src/test/java/com/auth0/android/provider/JwtTestUtils.java
  auth0/src/test/java/com/auth0/android/request/internal/BaseRequestTest.kt
Labels: CH: Fixed

#512 Proper migration for the new key sets was applied
  auth0/src/main/java/com/auth0/android/authentication/storage/CryptoUtil.java
  auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.kt
  auth0/src/test/java/com/auth0/android/authentication/storage/CryptoUtilTest.java
  auth0/src/test/java/com/auth0/android/authentication/storage/SecureCredentialsManagerTest.kt
Labels: CH: Fixed

#516 Prevent NPE when parsing email_verified boolean
  auth0/src/main/java/com/auth0/android/request/internal/UserProfileDeserializer.java
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationExceptionTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/UserProfileGsonTest.kt
Labels: CH: Fixed, review:small

#518 Replace mentions to expires_in with expires_at
  README.md
Labels: documentation, review:tiny
