Repository auth0/Auth0.Android, pull requests merged in 2021-11, with the labels that each got.

#526 Bump GSON dependency to 2.8.9
  auth0/build.gradle
Labels: CH: Security, dependencies, review:tiny

#527 Release 2.5.1
  CHANGELOG.md
  README.md
Labels: review:tiny

#519 Improve authenticated flow of the Credentials Manager
  README.md
  auth0/build.gradle
  auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.kt
  auth0/src/test/java/com/auth0/android/authentication/storage/SecureCredentialsManagerTest.kt
Labels: CH: Changed, medium
