Repository auth0/Auth0.Android, pull requests merged in 2021-07, with the labels that each got.

#497 Release 2.3.0
  CHANGELOG.md
  README.md
Labels: review:tiny

#486 Catch IOExceptions from response body InputStream
  auth0/src/main/java/com/auth0/android/request/internal/BaseRequest.kt
  auth0/src/test/java/com/auth0/android/request/internal/BaseRequestTest.kt
Labels: CH: Fixed

#498 Add support for OOB multi-factor authentication [SDK-2657]
  auth0/build.gradle
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.kt
  auth0/src/main/java/com/auth0/android/authentication/ParameterBuilder.kt
  auth0/src/main/java/com/auth0/android/result/Challenge.kt
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.kt
  auth0/src/test/java/com/auth0/android/util/AuthenticationAPIMockServer.kt
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  sample/build.gradle
Labels: CH: Added, medium

#501 Add federated option to the Web Auth Logout [SDK-2165]
  auth0/src/main/java/com/auth0/android/provider/LogoutManager.kt
  auth0/src/main/java/com/auth0/android/provider/WebAuthProvider.kt
  auth0/src/test/java/com/auth0/android/provider/LogoutManagerTest.java
  auth0/src/test/java/com/auth0/android/provider/WebAuthProviderTest.kt
  sample/build.gradle
  sample/src/main/java/com/auth0/sample/DatabaseLoginFragment.kt
  sample/src/main/res/layout/fragment_database_login.xml
Labels: CH: Added, review:small

#500 Add support for Recovery Code multi-factor authentication
  .editorconfig
  .gitattributes
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.kt
  auth0/src/main/java/com/auth0/android/authentication/ParameterBuilder.kt
  auth0/src/main/java/com/auth0/android/request/internal/CredentialsDeserializer.java
  auth0/src/main/java/com/auth0/android/request/internal/CredentialsDeserializer.kt
  auth0/src/main/java/com/auth0/android/result/Credentials.kt
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/CredentialsDeserializerMock.java
  auth0/src/test/java/com/auth0/android/request/internal/CredentialsDeserializerMock.kt
  auth0/src/test/java/com/auth0/android/result/CredentialsTest.java
  auth0/src/test/java/com/auth0/android/result/CredentialsTest.kt
  auth0/src/test/java/com/auth0/android/util/AuthenticationAPIMockServer.kt
  gradlew.bat
Labels: CH: Added, medium

#504 Fix MFA Challenge authentication and prevent sending the scope again
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.kt
  auth0/src/main/java/com/auth0/android/request/ServerResponse.kt
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.kt
  auth0/src/test/java/com/auth0/android/request/ServerResponseTest.kt
Labels: CH: Fixed, review:small

#505 Release 2.4.0
  CHANGELOG.md
  README.md
Labels: review:tiny
