Repository auth0/Auth0.Android, pull requests merged in 2022-06, with the labels that each got.

#565 Avoid parallel running in CI to avoid OOM issues
  .circleci/config.yml
Labels: review:tiny

#563 [SDK-3346] Implemented coroutine support
  auth0/build.gradle
  auth0/src/main/java/com/auth0/android/authentication/storage/CredentialsManager.kt
  auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.kt
  auth0/src/main/java/com/auth0/android/request/ProfileRequest.kt
  auth0/src/main/java/com/auth0/android/request/Request.kt
  auth0/src/main/java/com/auth0/android/request/SignUpRequest.kt
  auth0/src/main/java/com/auth0/android/request/internal/BaseAuthenticationRequest.kt
  auth0/src/main/java/com/auth0/android/request/internal/BaseRequest.kt
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.kt
  auth0/src/test/java/com/auth0/android/authentication/storage/CredentialsManagerTest.kt
  auth0/src/test/java/com/auth0/android/authentication/storage/SecureCredentialsManagerTest.kt
  auth0/src/test/java/com/auth0/android/management/UsersAPIClientTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/BaseRequestTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/MockAuthenticationRequest.java
  auth0/src/test/java/com/auth0/android/request/internal/MockRequest.java
Labels: CH: Added

#564 createdAt should be deserialized as ISO8601 UTC (not local time)
  auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.kt
  auth0/src/main/java/com/auth0/android/request/internal/GsonProvider.kt
  auth0/src/test/java/com/auth0/android/authentication/storage/SecureCredentialsManagerTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/CredentialsDeserializerTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/CredentialsGsonTest.kt
  auth0/src/test/java/com/auth0/android/request/internal/UserProfileGsonTest.kt
Labels: CH: Fixed

#566 [SDK-3082] Avoid config change to handle authentication
  auth0/src/main/AndroidManifest.xml
Labels: CH: Fixed, review:tiny

#574 Security: Update OkHttp to 4.10.0
  .circleci/config.yml
  auth0/build.gradle
Labels: CH: Security, dependencies

#571 [SDK-3354] Deserialize UserProfile.createdAt as ISO8601
  auth0/src/main/java/com/auth0/android/request/internal/UserProfileDeserializer.java
  auth0/src/test/java/com/auth0/android/request/internal/UserProfileGsonTest.kt
Labels: CH: Fixed, review:small

#569 [SDK-3144] Add user property to Credentials
  auth0/src/main/java/com/auth0/android/request/internal/Jwt.kt
  auth0/src/main/java/com/auth0/android/result/Credentials.kt
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationAPIClientTest.kt
  auth0/src/test/java/com/auth0/android/provider/JwtTestUtils.java
  auth0/src/test/java/com/auth0/android/result/CredentialsTest.kt
  auth0/src/test/java/com/auth0/android/util/AuthenticationAPIMockServer.kt
  sample/src/main/java/com/auth0/sample/DatabaseLoginFragment.kt
Labels: CH: Added, review:medium

#572 [SDK-3352] Expire credentials based on access token alone
  auth0/src/main/java/com/auth0/android/authentication/storage/BaseCredentialsManager.kt
  auth0/src/main/java/com/auth0/android/authentication/storage/CredentialsManager.kt
  auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.kt
  auth0/src/test/java/com/auth0/android/authentication/storage/CredentialsManagerTest.kt
  auth0/src/test/java/com/auth0/android/authentication/storage/SecureCredentialsManagerTest.kt
Labels: CH: Changed

#580 [SDK-3452] Network Exception Issue Fix
  auth0/src/main/java/com/auth0/android/authentication/AuthenticationException.kt
  auth0/src/test/java/com/auth0/android/authentication/AuthenticationExceptionTest.kt
Labels: CH: Fixed, review:medium

#579 [SDK-3358] Improve Android README
  README.md
Labels: review:medium
